Let the props freeze
lolleko/guesswho pull request #42
Opened 2016-10-01 20:23 UTC by FarukGamer

This function lets the props freeze if necessary.

Advantages:
- Improves server performance
- Prevents prop chaos

Disadvantages:
- Some props may stuck in air in 'Instant" mode

2016-10-01 20:43 UTC, lolleko requested changes
I posted some comments, about changes you should make, feel free to argue with me if something i requested doesn't seem right to you.

Once you are done I will do a quickt esting and then prepare the next update.

2016-10-01 20:43 UTC, lolleko commented on gamemodes/guesswho/gamemode/sh_config.lua
> +GM.PropFreezeEnabled = false -- if set to true, world props wont move.(default: false)
Please make PropFreezeEnabled a convar, by adding an `entry to gamemodes/guesswho/guesswho.txt` not via lua.

2016-10-01 20:43 UTC, lolleko commented on gamemodes/guesswho/gamemode/sh_config.lua
> +GM.PropFreezeIsTimed = true -- if set false, props will be instantly freezed.(default: true, setting false may cause props stuck on air(EXPERIMENTAL))
Probably remove these since they don't server any purpose? Why would you want to delay the freezing?

2016-10-01 20:43 UTC, lolleko commented on gamemodes/guesswho/gamemode/sh_config.lua
> +GM.PropFreezeDelay = 5 -- after how many seconds should the props freeze?.(default: 5, recommend between 5-7 seconds)
Rmove this aswell. Read above.

2016-10-01 20:43 UTC, lolleko commented on gamemodes/guesswho/gamemode/init.lua
> +AddCSLuaFile( "sh_propfreeze.lua")
Remove this since fil wont be needed on clients read more about that below.

2016-10-01 20:43 UTC, lolleko commented on gamemodes/guesswho/gamemode/sh_propfreeze.lua
> +-- Needs few language functions to understand it better
File should be Serverside only if it doesnt include any clientside code.

2016-10-01 20:43 UTC, lolleko requested changes
Added missing comments.

2016-10-01 20:43 UTC, lolleko commented on gamemodes/guesswho/gamemode/sh_propfreeze.lua
> +	if Enabled == true then
Always hook intoPosInit, And MapCleanup. In DoPropFreeze check if convar set with `GetConVar("gw_propfreeze_enabled"):GetBool()`.   So props will be frozen/unfrozen after a new round when convar changes. TL;DR `If convarforrozen then freeze else unfreeze end`

2016-10-01 20:43 UTC, lolleko commented on gamemodes/guesswho/gamemode/shared.lua
> +include("sh_propfreeze.lua")
Include in init.lua since script should be serverside only. Also change name to `sv_propfreeze.lua`

2016-10-01 21:22 UTC, FarukGamer commented
Wait, i forgot something

2016-10-01 21:55 UTC, FarukGamer commented on gamemodes/guesswho/gamemode/sh_config.lua
> +GM.PropFreezeEnabled = false -- if set to true, world props wont move.(default: false)
Did

2016-10-01 21:56 UTC, FarukGamer commented on gamemodes/guesswho/gamemode/sh_config.lua
> +GM.PropFreezeIsTimed = true -- if set false, props will be instantly freezed.(default: true, setting false may cause props stuck on air(EXPERIMENTAL))
A delay is needed to prevent on air stucked props

2016-10-01 21:57 UTC, FarukGamer commented on gamemodes/guesswho/gamemode/sh_config.lua
> +GM.PropFreezeDelay = 5 -- after how many seconds should the props freeze?.(default: 5, recommend between 5-7 seconds)
Dont worry their not hurting anymore ;)

2016-10-01 21:57 UTC, FarukGamer commented on gamemodes/guesswho/gamemode/init.lua
> +AddCSLuaFile( "sh_propfreeze.lua")
Did

2016-10-01 21:58 UTC, FarukGamer commented on gamemodes/guesswho/gamemode/sh_propfreeze.lua
> +-- Needs few language functions to understand it better
Did

2016-10-04 18:50 UTC, lolleko approved these changes

2016-10-11 22:26 UTC, merged

2016-10-11 22:27 UTC, JakeGC commented
Jesus, this took a while to merge

2016-10-11 22:31 UTC, lolleko commented
Ohh yeah update preparations for halloween 🗡 👻

2016-10-11 22:32 UTC, JakeGC commented
@lolleko http://spook.gdn